//
// Created by christoph on 02.06.19.
//

#ifndef CFD3D_PATHLINETRACER_HPP
#define CFD3D_PATHLINETRACER_HPP

#include "ParticleTracer.hpp"

/**
 * Path lines a are a type of characteristic lines of a flow.
 * To create path lines, one follows massless particles through time and space.
 */
class PathlineTracer : public TimeVaryingParticleTracer
{
public:
    /**
     * Sets the seeding positions of the particles to trace during the (time-dependent) simulation.
     * @param particleSeedingLocations The seeding locations of the particles to trace in world space.
     * @param gridOrigin The origin of the grid in world coordinates.
     * @param gridSize The size of the grid (i.e. the extent in x, y and z) of the grid.
     */
    virtual void setParticleSeedingLocations(
            const rvec3 &gridOrigin, const rvec3 &gridSize, const std::vector<rvec3> &particleSeedingLocations);

    /**
     * Integrates the position of all particles with the passed time step size.
     * @param t The current time in the simulation.
     * @param dt The time step to use for integrating the particle position.
     * @param imax Number of cells in x direction inside of the domain.
     * @param jmax Number of cells in y direction inside of the domain.
     * @param kmax Number of cells in z direction inside of the domain.
     * @param U The velocities in x direction.
     * @param V The velocities in y direction.
     * @param W The velocities in z direction.
     */
    virtual void timeStep(Real t, Real dt, int imax, int jmax, int kmax, Real *U, Real *V, Real *W);

    /**
     * Get the characteristic lines generated by the calls @see timeStep.
     * @return The characteristic lines (an array containing the arrays of line points).
     */
    virtual std::vector<std::vector<rvec3>> getLines();

private:
    rvec3 gridOrigin, gridSize;
    size_t numParticles;
    std::vector<rvec3> particleSeedingLocations;
    std::vector<std::vector<rvec3>> lines;
};

#endif //CFD3D_PATHLINETRACER_HPP
